name: Build and Deploy React App to Github Pages
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    # Create the .env file dynamically during the workflow run
    - name: Create .env file
      run: |
        echo "EMAILJS_PUBLIC_KEY=${{ secrets.EMAILJS_PUBLIC_KEY }}" >> .env
        echo "EMAILJS_SERVICE_ID=${{ secrets.EMAILJS_SERVICE_ID }}" >> .env
        echo "EMAILJS_TEMPLATE_ID=${{ secrets.EMAILJS_TEMPLATE_ID }}" >> .env

    - name: Verify .env file creation
      run: cat .env
      
    - name: Deploy 
      run: |
        git config --global user.name name:${{ secrets.GITHUB_USERNAME }}
        git config --global user.email email:${{ secrets.GITHUB_EMAIL }}
        git remote set-url origin https://access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}   
        npm run deploy
