name: Build and Deploy React App to Github Pages
on:
    push:
        branches: [ main ]
jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Build
          run: npm install

        - name: Test
          run: npm run test
        
        - name: Deploy with gh-pages
          run: |
            git config --global user.email git:${GITHUB_USERNAME}
            git config --global user.name git:${secrets.GITHUB_EMAIL}
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            npm run deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
            GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
            

            